8080:
  /:
    alias: 后端服务
    backends:
    - alias: 德亚姐
      url: http://localhost:3000
    - alias: 德亚云桌面
      url: http://localhost:3001
    current_backend: 1
  /mock:
    alias: mock服务
    backends: []
    current_backend: null
